// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMEDX0KEhMBnbVKYpx9HHhasleAppGK3E',
    appId: '1:464927983622:web:a6564aa10a146f9af21b87',
    messagingSenderId: '464927983622',
    projectId: 'ejemplofirebase-38f98',
    authDomain: 'ejemplofirebase-38f98.firebaseapp.com',
    databaseURL: 'https://ejemplofirebase-38f98-default-rtdb.firebaseio.com',
    storageBucket: 'ejemplofirebase-38f98.firebasestorage.app',
    measurementId: 'G-P7JNPZYK1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvA0B72j81_7HqG_zxHFSGe_tYFFkItG4',
    appId: '1:464927983622:android:f623e4259f26a9dbf21b87',
    messagingSenderId: '464927983622',
    projectId: 'ejemplofirebase-38f98',
    databaseURL: 'https://ejemplofirebase-38f98-default-rtdb.firebaseio.com',
    storageBucket: 'ejemplofirebase-38f98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb4kafY5xXpDW2yLCQADcWHGEZRkXfu18',
    appId: '1:464927983622:ios:766abc45470eb5d2f21b87',
    messagingSenderId: '464927983622',
    projectId: 'ejemplofirebase-38f98',
    databaseURL: 'https://ejemplofirebase-38f98-default-rtdb.firebaseio.com',
    storageBucket: 'ejemplofirebase-38f98.firebasestorage.app',
    iosBundleId: 'com.stockmind.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb4kafY5xXpDW2yLCQADcWHGEZRkXfu18',
    appId: '1:464927983622:ios:766abc45470eb5d2f21b87',
    messagingSenderId: '464927983622',
    projectId: 'ejemplofirebase-38f98',
    databaseURL: 'https://ejemplofirebase-38f98-default-rtdb.firebaseio.com',
    storageBucket: 'ejemplofirebase-38f98.firebasestorage.app',
    iosBundleId: 'com.stockmind.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMEDX0KEhMBnbVKYpx9HHhasleAppGK3E',
    appId: '1:464927983622:web:231f8d35aca51771f21b87',
    messagingSenderId: '464927983622',
    projectId: 'ejemplofirebase-38f98',
    authDomain: 'ejemplofirebase-38f98.firebaseapp.com',
    databaseURL: 'https://ejemplofirebase-38f98-default-rtdb.firebaseio.com',
    storageBucket: 'ejemplofirebase-38f98.firebasestorage.app',
    measurementId: 'G-5T0H31VE5M',
  );
}
